// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqra8e7ksJwzFsTtF7nprSX2jGyvAcvRY',
    appId: '1:464177351985:web:674be49ed0359276027410',
    messagingSenderId: '464177351985',
    projectId: 'almarsa-app',
    authDomain: 'almarsa-app.firebaseapp.com',
    databaseURL: 'https://almarsa-app-default-rtdb.firebaseio.com',
    storageBucket: 'almarsa-app.firebasestorage.app',
    measurementId: 'G-MEHJ1S4CWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWE-gxBcLo0BIhxiMa1M1K0ztjz3jNW4',
    appId: '1:464177351985:android:df0e86d6c938a364027410',
    messagingSenderId: '464177351985',
    projectId: 'almarsa-app',
    databaseURL: 'https://almarsa-app-default-rtdb.firebaseio.com',
    storageBucket: 'almarsa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ogojzXU8dnIalXkwgsDpNErxYWakaA8',
    appId: '1:464177351985:ios:b36e2c430b100ba6027410',
    messagingSenderId: '464177351985',
    projectId: 'almarsa-app',
    databaseURL: 'https://almarsa-app-default-rtdb.firebaseio.com',
    storageBucket: 'almarsa-app.firebasestorage.app',
    iosBundleId: 'com.example.almarsa',
  );
}
